# BEGIN_KITTY_THEME
# rose-pine
include current-theme.conf
# END_KITTY_THEME
font_family ComicShannsMono Nerd Font Mono
font_size 14.0
enable_audio_bell false
symbol_map U+0400-U+04FF Monofur Nerd Font Mono
